Fixed the generation of urls to work with plugin table classes
loadsys/CakePHP-Sitemap pull request #52
Opened 2017-08-09 13:45 UTC by davidyell

Following on from fixing the loading of plugin table classes, it seems that generating links for plugin table classes has the same issue.

I have fixed that. I have stuck with the deprecated method because upgrading the plugin is outside of scope for this pull request, and would also push the minimum requirement for the plugin to CakePHP 3.4+, and changing the requirements are outside the scope of this pull request.

2017-08-22 11:01 UTC, davidyell commented
If you get a chance, please can you take a look at this for me @justinyost thanks!

2018-01-17 01:46 UTC, justinyost requested changes
Simple change and I'll merge.

2018-01-17 01:46 UTC, justinyost commented on tests/TestCase/Model/Behavior/SitemapBehaviorTest.php
> +	public function testReturnUrlForPluginEntity() {
@davidyell Can I get a docblock and I'm good.

2018-01-17 14:48 UTC, davidyell commented on tests/TestCase/Model/Behavior/SitemapBehaviorTest.php
> +	public function testReturnUrlForPluginEntity() {
![Ooh! Can do!](https://i.imgur.com/5gct8Dx.gif)

2018-01-24 15:35 UTC, davidyell commented
Seems that the Travis config is relying on a url which is a 404 now.

2018-02-01 01:55 UTC, justinyost commented
@davidyell I'm looking into this and for some crazy reason Github isn't sending me notifications which is why it's taking so long for me to respond

2018-02-01 02:27 UTC, justinyost commented
@davidyell Rebase and your PR will be fixed and I can merge. Once again I'm sorry I didn't swap my notifications for this org to go to my personal email.

2018-02-01 09:21 UTC, davidyell commented
No problem @justinyost I'll get this sorted today.

2018-02-01 19:24 UTC, justinyost approved these changes
LGTM 👍

2018-02-01 19:30 UTC, merged

2018-02-01 19:36 UTC, davidyell commented
Great, thanks @justinyost